# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_filtrs_wrappers", use_symbols = TRUE, package_name = "filtrs")

#' @docType package
#' @usage NULL
#' @useDynLib filtrs, .registration = TRUE
NULL

#'
#'Perform a Whittaker-Eilers smoother.
#'
#'Insanely fast and reliable smoothing and interpolation with the Whittaker-Eilers method.
#'
#'@param y numeric vector to smooth (must be of class double!!)
#'@param lambda an number of class double for smoothing control. The larger the lambda, the smoother the data.
#'@param order an integer for smoothing control. A higher order means the Whittaker will consider more adjacent elements while smoothing.
#'
#'@examples
#'data("airquality")
#'
#'airquality$Ozone_smooth <- 
#'  fil_wt(as.double(airquality$Ozone), 10, 2)
#'
#'plot(airquality$Ozone, type = "l", xlab = "Days", ylab = "Ozone")
#'lines(airquality$Ozone_smooth, co = "red")
#'@export
#'
fil_wt <- function(y, lambda, order) .Call(wrap__fil_wt, y, lambda, order)


# nolint end
